# Generated by Django 6.0.4 on 2026-05-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_comment_updated_at_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Comment like', 'verbose_name_plural': 'Comment likes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventlike',
            options={'verbose_name': 'Event like', 'verbose_name_plural': 'Event likes'},
        ),
    ]
