# Generated by Django 6.0.4 on 2026-05-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_max_participants_eventregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='is_first_time',
            new_name='eating_meat',
        ),
    ]
