# Generated by Django 6.0.4 on 2026-05-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_is_first_time_eventregistration_eating_meat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='comment',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='experience',
            field=models.CharField(choices=[('parents', 'Parents'), ('teacher', 'Teacher'), ('psychologist', 'Psychologist'), ('trauma_pedagogy', 'Trauma pedagogy'), ('social_worker', 'Social worker'), ('other', 'Other')], max_length=50),
        ),
    ]
