# Generated by Django 6.0.4 on 2026-05-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='parent',
        ),
    ]
