# Generated by Django 6.0.4 on 2026-05-12 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('education_materials', '0002_remove_articlecomment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Article Comment', 'verbose_name_plural': 'Article Comments'},
        ),
        migrations.AlterModelOptions(
            name='articlecommentlike',
            options={'verbose_name': 'Article Comment Like', 'verbose_name_plural': 'Article Comment Likes'},
        ),
        migrations.AlterModelOptions(
            name='articlelike',
            options={'verbose_name': 'Article Like', 'verbose_name_plural': 'Article Likes'},
        ),
        migrations.AlterModelOptions(
            name='articlesection',
            options={'ordering': ['order'], 'verbose_name': 'Article Section', 'verbose_name_plural': 'Article Sections'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterUniqueTogether(
            name='articlecommentlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='articlesection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='articlecommentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_article_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_article_like'),
        ),
        migrations.AddConstraint(
            model_name='articlesection',
            constraint=models.UniqueConstraint(fields=('article', 'slug'), name='unique_article_section_slug'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_favorite'),
        ),
    ]
