# Generated by Django 6.0.4 on 2026-05-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_cancelled_at_appointment_cancelled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='scheduling.availabilityslot'),
        ),
    ]
