# Generated by Django 6.0.4 on 2026-04-26 11:38

import django.db.models.deletion
import phonenumber_field.modelfields
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA')),
                ('city', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('education', models.CharField(choices=[('psychologist', 'Psychologist'), ('trauma informed educator', 'Trauma informed educator'), ('other', 'Other')], default='other', max_length=30)),
                ('education_other', models.CharField(blank=True, max_length=255, null=True)),
                ('cares_for_children', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_avatar_file_path)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_processing_consent_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=profiles.models.specialist_avatar_file_path)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA')),
                ('city', models.CharField(max_length=150)),
                ('specialisation', models.CharField(max_length=255)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('bio', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_processing_consent_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialist Profile',
                'verbose_name_plural': 'Specialist Profiles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=profiles.models.specialist_document_file_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.specialistprofile')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
