# Generated by Django 6.0.4 on 2026-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
